[phases.setup]
nixPkgs = ["...", "jdk17", "maven"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[start]
cmd = "java -Xmx2g -Xms512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication -XX:MaxRAMPercentage=25.0 -jar target/ai-digital-enrollment-1.0.0-SNAPSHOT.jar"
